"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from investec_za_pb.types import BaseModel
from investec_za_pb.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class DocumentRequestTypedDict(TypedDict):
    account_id: str
    r"""AccountId Id"""
    document_type: str
    r"""Document Type"""
    document_date: str
    r"""Document Date"""


class DocumentRequest(BaseModel):
    account_id: Annotated[
        str,
        pydantic.Field(alias="accountId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""AccountId Id"""

    document_type: Annotated[
        str,
        pydantic.Field(alias="documentType"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Document Type"""

    document_date: Annotated[
        str,
        pydantic.Field(alias="documentDate"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Document Date"""
