"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from enum import Enum


class OAuth2Scope(str, Enum):
    r"""Available scopes for the Oauth2 OAuth 2.0 scheme (clientCredentials flow).

    The authentication flow complies to standard Oauth2 protocol but also requires an.<br>  **x-api-key** as an additional header. <br>Also remember to include **grant_type: client_credentials** (x-www-form-urlencoded) in the body of the request
    """

    ACCOUNTS = "accounts"
    r"""Account information"""

    BALANCES = "balances"
    r"""Account balance information"""

    TRANSACTIONS = "transactions "
    r"""Transaction history"""

    TRANSFERS = "transfers"
    r"""Inter account transfer"""

    BENEFICIARYPAYMENTS = "beneficiarypayments"
    r"""Beneficiary payments"""

    DOCUMENTS_STATEMENTS = "documents.statements"
    r"""Statements retrieval"""

    DOCUMENTS_TAXCERTIFICATES = "documents.taxcertificates"
    r"""Tax certificates retrieval"""
